id: I5B3003A7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T12:04:31+00:00'
last_modified: '2022-06-07T17:35:55.794843+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W30022
  title: ཕར་ཕྱིན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    79C8:
      image_group_id: I5754
      title: ''
      total_pages: 1211
      order: 1
      base_file: 79C8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
