id: P003106
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:40:40.732652
source_metadata:
  id: bdr:W30022
  title: ཕར་ཕྱིན།
  author: ''
  volumes:
    f4e0e6e9fd9149b68663af218a119148:
      image_group_id: I5754
      title: ''
      volume_number: 1
      total_pages: 1211
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
